#' @param .output Function output to check.
#' @param .assertion Assertion to apply.
#' @param ... Additional arguments passed to the assertion.
#' @param .assertion_expr Optional expression used in error messages. This is
#'   supplied by typedr-generated code.
#'
#' @export
#' @return `check_output()` returns `.output` if it satisfies the assertion and
#'   throws an error otherwise.
#' @rdname check_arg
#'
#' @importFrom rlang call_name expr_deparse enexpr try_fetch caller_env %||%
#' @importFrom cli cli_abort
check_output <- function(.output, .assertion, ..., .assertion_expr = NULL) {
  if (is_null(.assertion_expr)) {
    .assertion_expr <- enexpr(.assertion)
  }

  asset_nm <- if (is_call(.assertion_expr)) {
    expr_deparse(.assertion_expr)
  } else if (is_character(.assertion_expr)) {
    .assertion_expr
  } else {
    expr_name(.assertion_expr)
  }

  res_type <- .format_type(.output) # R/utils.R

  val <- try_fetch(.assertion(.output, ...), error = identity)
  if (inherits(val, "error")) {
    val$call <- .assertion_expr
    cli_abort(
      c(
        "Return value does not satisfy the required {.cls Type()}.",
        x = "Expected {.cls {asset_nm}} return value, got {res_type}."
      ),
      class = c(
        "typedr_return_error",
        "typedr_check_output_error",
        "typedr_error"
      ),
      parent = val,
      call = caller_env()
    )
  }
  .output
}

#' Check Argument Types and Return Type
#'
#' These functions are generated by typedr's `?` syntax and are usually not
#' called directly. Prefer the syntaxes described in `?declare`. `check_arg()`
#' checks that an argument satisfies an assertion and can turn it into an active
#' binding so later assignments are checked as well. `check_output()` checks that
#' a value, usually a return value, satisfies an assertion.
#'
#' typedr reports failures with cli messages and structured rlang-compatible
#' condition classes such as `typedr_type_error`, `typedr_assign_error`, and
#' `typedr_return_error`. These classes make errors easier to test, catch, and
#' diagnose than plain message-only failures.
#'
#' @param .arg Function argument to check.
#' @param .assertion Assertion to apply.
#' @param ... Additional arguments passed to the assertion.
#' @param .bind Whether to actively bind the argument so later assignments must
#'   also satisfy the assertion.
#' @return `check_arg()` returns `NULL` invisibly and is called for side effects.
#'
#' @export
#' @importFrom rlang caller_env enexpr enexprs is_missing as_name as_label
#' @importFrom rlang call_name caller_call expr eval_bare call2 try_fetch
#' @importFrom cli cli_abort
check_arg <- function(.arg, .assertion, ..., .bind = FALSE) {
  call <- caller_env()
  arg_expr <- enexpr(.arg)
  .assertion_expr <- enexpr(.assertion)
  var_nm <- if (is_symbol(arg_expr)) as_name(arg_expr) else as_label(arg_expr)

  if (is_missing(.arg)) {
    fun_nm <- call_name(caller_call())
    cli_abort(
      c(
        "Invalid {.cls Type()} of `{.field {var_nm}}` to `{.field {fun_nm}()}`.",
        "x" = "Argument `{.field {var_nm}}` is missing."
      ),
      class = c(
        "typedr_missing_argument_error",
        "typedr_type_error",
        "typedr_check_arg_error",
        "typedr_error"
      ),
      call = call
    )
  }

  if (.bind) {
    assertion_expr <- enexpr(.assertion)
    dots_exprs <- enexprs(...)

    f <- eval_bare(
      expr(
        local(
          {
            val <- !!.arg
            function(assigned_value) {
              if (!is_missing(assigned_value)) {
                # fix
                tmp <- try_fetch(
                  !!call2(assertion_expr, expr(assigned_value), !!!dots_exprs),
                  error = identity
                )
                arg_nm <- !!var_nm
                if (inherits(tmp, "error")) {
                  tmp$call <- !!.assertion_expr
                  cli_abort(
                    "Assigned value to `{.field {arg_nm}}` doesn't satisfy the assertion.",
                    class = c(
                      "typedr_assign_error",
                      "typedr_check_arg_error",
                      "typedr_error"
                    ),
                    parent = tmp,
                    call = !!call
                  )
                }
                val <<- tmp
              }
              val
            }
          },
          envir = !!call
        )
      ),
      env = call
    )

    attr(f, "srcref") <- NULL
    if (env_has(call, var_nm, inherit = FALSE)) {
      env_unbind(call, var_nm, inherit = FALSE)
    }
    env_bind_active(call, !!var_nm := f)
  }

  val <- try_fetch(.assertion(.arg, ...), error = identity)
  if (inherits(val, "error")) {
    val$call <- .assertion_expr
    fun_nm <- call_name(caller_call())
    cli_abort(
      "Invalid {.cls Type()} of `{.field {var_nm}}` to `{.field {fun_nm}()}`.",
      class = c("typedr_type_error", "typedr_check_arg_error", "typedr_error"),
      parent = val,
      call = call
    )
  }

  invisible(NULL)
}

#' @param .guard Guard expression used to decide whether `.assertion` applies.
#' @param .severity Whether a guarded assertion failure should error or warn.
#' @param .inactive Whether a supplied argument should be ignored, warned, or
#'   rejected when `.guard` does not match.
#'
#' @export
#' @rdname check_arg
check_dependent_arg <- function(
  .arg,
  .guard,
  .assertion,
  .severity = c("error", "warning"),
  .inactive = c("ignore", "warning", "error")
) {
  call <- caller_env()
  arg_expr <- enexpr(.arg)
  guard_expr <- .guard
  assertion_expr <- enexpr(.assertion)
  var_nm <- if (is_symbol(arg_expr)) as_name(arg_expr) else as_label(arg_expr)
  .severity <- arg_match(.severity)
  .inactive <- arg_match(.inactive)

  if (!typedr_eval_guard(guard_expr, call)) {
    arg_missing <- is_missing(.arg)
    if (arg_missing) {
      env_bind(call, !!!set_names(list(NULL), var_nm))
    }
    if (.inactive != "ignore" && !arg_missing) {
      typedr_inactive_arg_cnd(
        var_nm,
        guard_expr,
        severity = .inactive,
        call = call
      )
    }
    return(invisible(NULL))
  }

  guard_label <- expr_deparse(guard_expr)
  assertion_label <- expr_deparse(assertion_expr)
  message <- c(
    "Invalid dependent {.cls Type()} of `{.field {var_nm}}`.",
    "i" = "Guard `{.field {guard_label}}` matched, so `{.field {var_nm}}` must satisfy {.cls {assertion_label}}."
  )

  if (is_missing(.arg)) {
    message <- c(
      message,
      "x" = "Argument `{.field {var_nm}}` is missing."
    )
    if (.severity == "warning") {
      .cli_warn_bullets(
        message,
        class = c(
          "typedr_dependency_warning",
          "typedr_check_arg_warning",
          "typedr_warning"
        ),
        call = call
      )
      return(invisible(NULL))
    }

    cli_abort(
      message,
      class = c(
        "typedr_missing_argument_error",
        "typedr_dependency_error",
        "typedr_type_error",
        "typedr_check_arg_error",
        "typedr_error"
      ),
      call = call
    )
  }

  val <- try_fetch(.assertion(.arg), error = identity)
  if (!inherits(val, "error")) {
    return(invisible(NULL))
  }

  val$call <- assertion_expr

  if (.severity == "warning") {
    .cli_warn_bullets(
      message,
      class = c(
        "typedr_dependency_warning",
        "typedr_check_arg_warning",
        "typedr_warning"
      ),
      call = call
    )
    return(invisible(NULL))
  }

  cli_abort(
    message,
    class = c(
      "typedr_dependency_error",
      "typedr_type_error",
      "typedr_check_arg_error",
      "typedr_error"
    ),
    parent = val,
    call = call
  )
}

typedr_inactive_arg_cnd <- function(var_nm, guard_expr, severity, call) {
  guard_label <- expr_deparse(guard_expr)
  message <- c(
    "!" = "Argument `{.field {var_nm}}` is inactive.",
    "i" = "Guard `{.field {guard_label}}` did not match, so `{.field {var_nm}}` will not take effect."
  )

  if (severity == "warning") {
    .cli_warn_bullets(
      message,
      class = c(
        "typedr_dependency_inactive_warning",
        "typedr_check_arg_warning",
        "typedr_warning"
      ),
      call = call
    )
    return(invisible(NULL))
  }

  cli_abort(
    message,
    class = c(
      "typedr_dependency_inactive_error",
      "typedr_check_arg_error",
      "typedr_error"
    ),
    call = call
  )
}

typedr_eval_guard <- function(guard, env) {
  if (is_call(guard, "(")) {
    return(typedr_eval_guard(guard[[2]], env))
  }

  if (is_call(guard, "!")) {
    return(!typedr_eval_guard(guard[[2]], env))
  }

  if (is_call(guard, "|")) {
    return(
      typedr_eval_guard(guard[[2]], env) ||
        typedr_eval_guard(guard[[3]], env)
    )
  }

  if (is_call(guard, "&")) {
    return(
      typedr_eval_guard(guard[[2]], env) &&
        typedr_eval_guard(guard[[3]], env)
    )
  }

  if (is_call(guard, ":") && length(guard) == 3L) {
    return(typedr_eval_guard_condition(guard[[2]], guard[[3]], env))
  }

  cli_abort(
    c(
      "Invalid dependent argument guard.",
      i = "Use guards like `{.code a1:Integer()}`, combined with `{.code |}` and `{.code &}`."
    ),
    class = c(
      "typedr_guard_error",
      "typedr_check_arg_error",
      "typedr_error"
    ),
    call = env
  )
}

typedr_eval_guard_condition <- function(arg, assertion_expr, env) {
  if (!is_symbol(arg)) {
    cli_abort(
      "Guard left-hand side must be an argument name.",
      class = c(
        "typedr_guard_error",
        "typedr_check_arg_error",
        "typedr_error"
      ),
      call = env
    )
  }

  missing_guard <- typedr_is_missing_guard(assertion_expr)
  if (missing_guard) {
    return(typedr_arg_is_missing(arg, env))
  }

  assertion <- eval_bare(assertion_expr, env = env)
  if (inherits(assertion, "assertion_factory")) {
    assertion <- assertion()
  }

  if (!inherits(assertion, "typedr_assertion")) {
    cli_abort(
      "Guard right-hand side must be a typedr assertion.",
      class = c(
        "typedr_guard_error",
        "typedr_check_arg_error",
        "typedr_error"
      ),
      call = env
    )
  }

  value <- try_fetch(eval_bare(arg, env = env), error = identity)
  if (inherits(value, "error")) {
    cli_abort(
      "Guard argument `{.field {as_name(arg)}}` could not be evaluated.",
      class = c(
        "typedr_guard_error",
        "typedr_check_arg_error",
        "typedr_error"
      ),
      parent = value,
      call = env
    )
  }

  res <- try_fetch(assertion(value), error = identity)
  !inherits(res, "error")
}

typedr_is_missing_guard <- function(assertion_expr) {
  if (is_symbol(assertion_expr)) {
    return(identical(as_name(assertion_expr), "Missing"))
  }
  is_call(assertion_expr) &&
    length(assertion_expr) == 1L &&
    identical(call_name(assertion_expr), "Missing")
}

typedr_arg_is_missing <- function(arg, env) {
  missing_arg <- try_fetch(
    eval_bare(call2("missing", arg), env = env),
    error = identity
  )
  if (inherits(missing_arg, "error")) {
    cli_abort(
      "Guard argument `{.field {as_name(arg)}}` could not be evaluated.",
      class = c(
        "typedr_guard_error",
        "typedr_check_arg_error",
        "typedr_error"
      ),
      parent = missing_arg,
      call = env
    )
  }
  if (missing_arg) {
    return(TRUE)
  }

  value <- try_fetch(eval_bare(arg, env = env), error = identity)
  if (inherits(value, "error")) {
    cli_abort(
      "Guard argument `{.field {as_name(arg)}}` could not be evaluated.",
      class = c(
        "typedr_guard_error",
        "typedr_check_arg_error",
        "typedr_error"
      ),
      parent = value,
      call = env
    )
  }

  is_null(value)
}

#' @param x Variable name as a string.
#' @param assertion Assertion to apply. If `NULL`, the assertion is inferred from
#'   `value`.
#' @param value Optional initial value.
#' @param const Whether to declare `x` as a constant.
#'
#' @export
#' @importFrom rlang caller_env enexpr is_null expr eval_bare call2 try_fetch
#' @importFrom rlang env env_bind_active env_has env_unbind
#' @importFrom cli cli_abort
declare <- function(x, assertion = NULL, value, const = FALSE) {
  call <- caller_env()
  f_env <- env(parent = call)
  assertion_expr <- enexpr(assertion)

  if (!is_null(assertion)) {
    assertion_quoted <- assertion_expr
    if (inherits(assertion, "assertion_factory")) {
      assertion <- assertion()
      assertion_quoted <- call2(assertion_expr)
    }
  } else {
    assertion_quoted <- infer_implicit_assignment_call(value)
    assertion_expr <- assertion_quoted
    assertion <- eval_bare(assertion_quoted, env = call)
  }

  ## is value provided ?
  if (!is_missing(value)) {
    val <- try_fetch(assertion(value), error = identity)
    if (inherits(val, "error")) {
      val$call <- assertion_expr
      cli_abort(
        "Invalid initial value for `{.field {x}}`.",
        class = c(
          "typedr_initial_error",
          "typedr_declare_error",
          "typedr_error"
        ),
        parent = val
      )
    }
    value <- .apply_typedr_attrs(val, x, assertion_expr, const) # R/utils.R
  } else {
    # NULL is accepted as a first value even if it doesn't pass the check
    # this is because we're very flexible with types, the alternative would be
    # to force the user to define a default object when value is missing in the assertion factory
    value <- NULL
  }

  if (const) {
    f <- eval_bare(
      expr(
        local({
          val <- !!value
          function(assigned_value) {
            if (!is_missing(assigned_value)) {
              cli_abort(
                "Can't assign to a constant `{.field {x}}`.",
                class = c(
                  "typedr_constant_error",
                  "typedr_declare_error",
                  "typedr_error"
                )
              )
            }
            .typedr_unwrap(val) # R/utils.R
          }
        })
      ),
      env = f_env
    )
  } else {
    env_bind(f_env, .typedr_assertion_expr = assertion_quoted)

    f <- eval_bare(
      expr(
        local({
          val <- !!value
          function(assigned_value) {
            if (!is_missing(assigned_value)) {
              tmp <- try_fetch(
                !!call2(assertion_quoted, expr(assigned_value)),
                error = identity
              )
              rt_assertion <- attr(val, "typedr_assertion", exact = TRUE) %||%
                .typedr_assertion_expr
              if (inherits(tmp, "error")) {
                tmp$call <- rt_assertion
                cli_abort(
                  "Assigned value to `{.field {x}}` doesn't satisfy the assertion.",
                  class = c(
                    "typedr_assign_error",
                    "typedr_declare_error",
                    "typedr_error"
                  ),
                  parent = tmp
                )
              }
              val <<- .apply_typedr_attrs(tmp, x, rt_assertion, const = FALSE) # R/utils.R
            }
            .typedr_unwrap(val) # R/utils.R
          }
        })
      ),
      env = f_env
    )
  }

  attr(f, "srcref") <- NULL # so it's not set to old definition
  if (env_has(call, x, inherit = FALSE)) {
    env_unbind(call, x, inherit = FALSE)
  }
  env_bind_active(call, !!x := f)

  return(invisible(.typedr_unwrap(value))) # R/utils.R
}
