on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

name: Package Check

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  R-CMD-check:
    uses: ./.github/workflows/R-CMD-check.yaml
    secrets: inherit

  test-coverage:
    uses: ./.github/workflows/test-coverage.yaml
    secrets: inherit
